#spring.application.name=ghbliapi
stability.api.base-url=https://api.stability.ai
stability.api.key=${STABILITY_API_KEY}

# Increase upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# HTTP client timeouts
spring.mvc.async.request-timeout=120000

feign.encode.encoder-class = org.springframework.openfeign.support.SpringEncoder